/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create auth cookie */
        post: operations["createAuth"];
        /** Clear auth cookie */
        delete: operations["deleteAuth"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get posts */
        get: operations["getPosts"];
        put?: never;
        /** Create post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get post by ID */
        get: operations["getPostById"];
        put?: never;
        post?: never;
        /** Delete post by ID */
        delete: operations["deletePostById"];
        options?: never;
        head?: never;
        /** Update post by ID */
        patch: operations["updatePostById"];
        trace?: never;
    };
    "/folder-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get folder data by path */
        get: operations["getFolderData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error401: {
            message: string;
        };
        FolderDataItemMeta: {
            createdAt: number;
            updatedAt: number;
        };
        FolderDataItemBase: {
            name: string;
            path: string;
            _meta: components["schemas"]["FolderDataItemMeta"];
        };
        /** @enum {string} */
        ItemType: "FOLDER" | "FILE";
        FolderDataItemFileBase: components["schemas"]["FolderDataItemBase"] & {
            itemType: components["schemas"]["ItemType"] & "FILE";
            src: string;
        };
        /** @enum {string} */
        FileType: "IMAGE" | "VIDEO" | "AUDIO" | "UNKNOWN";
        FolderDataItemAudio: components["schemas"]["FolderDataItemFileBase"] & {
            fileType: components["schemas"]["FileType"] & "AUDIO";
            metadata: {
                album: string | null;
                bpm: number | null;
                year: number | null;
                artists: string[];
                bitrate: number | null;
                duration: number | null;
            };
        };
        FolderDataSize: {
            width: number;
            height: number;
        };
        FolderDataItemImage: components["schemas"]["FolderDataItemFileBase"] & {
            fileType: components["schemas"]["FileType"] & "IMAGE";
            metadata: components["schemas"]["FolderDataSize"];
        };
        FolderDataItemVideo: components["schemas"]["FolderDataItemFileBase"] & {
            fileType: components["schemas"]["FileType"] & "VIDEO";
            metadata: components["schemas"]["FolderDataSize"];
        };
        FolderDataItemUnknown: components["schemas"]["FolderDataItemFileBase"] & {
            fileType: components["schemas"]["FileType"] & "UNKNOWN";
        };
        FolderDataItemFile: components["schemas"]["FolderDataItemAudio"] | components["schemas"]["FolderDataItemImage"] | components["schemas"]["FolderDataItemVideo"] | components["schemas"]["FolderDataItemUnknown"];
        PostAttachment: components["schemas"]["FolderDataItemFile"] & {
            _meta: components["schemas"]["FolderDataItemMeta"] & {
                id: string;
            };
        };
        PostResponse: {
            _meta: {
                id: string;
                createdAt: number;
                updatedAt: number;
            };
            text: string;
            attachments: components["schemas"]["PostAttachment"][];
        };
        PostsResponse: {
            _meta: {
                isEnd: boolean;
                page: number;
            };
            rows: components["schemas"]["PostResponse"][];
        };
        Error400: {
            message: string;
        };
        PostCreateRequest: {
            files: string[];
            text: string;
        };
        Error404: {
            message: string;
        };
        PostUpdateRequest: {
            text: string;
            attachments: (components["schemas"]["PostAttachment"] | null)[];
            files: string[];
        };
        FolderDataItemFolder: components["schemas"]["FolderDataItemBase"] & {
            itemType: components["schemas"]["ItemType"] & "FOLDER";
        };
        FolderDataResponse: {
            folders: components["schemas"]["FolderDataItemFolder"][];
            files: components["schemas"]["FolderDataItemFile"][];
            file: components["schemas"]["FolderDataItemFile"] | null;
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAuth: {
        parameters: {
            query?: {
                /** @description JWT token to set in auth cookie */
                jwt?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jwt: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error401"];
                };
            };
        };
    };
    deleteAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string|null} */
                        jwt: null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error401"];
                };
            };
        };
    };
    getPosts: {
        parameters: {
            query?: {
                /** @description Page number (0-based) */
                page?: number;
                /** @description Items per page */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error400"];
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error400"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error401"];
                };
            };
        };
    };
    getPostById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error404"];
                };
            };
        };
    };
    deletePostById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error401"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error404"];
                };
            };
        };
    };
    updatePostById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["PostUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error400"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error401"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error404"];
                };
            };
        };
    };
    getFolderData: {
        parameters: {
            query: {
                /** @description Path inside folder-data (e.g. path/to/folder) */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDataResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error404"];
                };
            };
        };
    };
}
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const itemTypeValues: ReadonlyArray<components["schemas"]["ItemType"]> = ["FOLDER", "FILE"];
export const folderDataItemFileBaseItemTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemFileBase"]["itemType"]> = ["FILE"];
export const fileTypeValues: ReadonlyArray<components["schemas"]["FileType"]> = ["IMAGE", "VIDEO", "AUDIO", "UNKNOWN"];
export const folderDataItemAudioFileTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemAudio"]["fileType"]> = ["AUDIO"];
export const folderDataItemImageFileTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemImage"]["fileType"]> = ["IMAGE"];
export const folderDataItemVideoFileTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemVideo"]["fileType"]> = ["VIDEO"];
export const folderDataItemUnknownFileTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemUnknown"]["fileType"]> = ["UNKNOWN"];
export const folderDataItemFolderItemTypeValues: ReadonlyArray<components["schemas"]["FolderDataItemFolder"]["itemType"]> = ["FOLDER"];
